server:
  http2:
    enabled: true
  port: '8080'
  ssl:
    enabled: true
    key-store: '${TLS_KEYSTORE_PATH:certs/sh_keystore.jks}'
    key-store-password: '${TLS_KEYSTORE_SECRET:secret}'

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true