---
version: "3.9"
services:
  local-postgres-compose:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network



#  db:
#      image: postgres:15.2
#      ports:
#        - "5432:5432"
#      restart: always
#      volumes:
#        - postgres-data:/data/postgres
#      environment:
#        - POSTGRES_USER=postgres
#        - POSTGRES_PASSWORD=postgres
#volumes:
#  postgres-data:
#    driver: local


networks:
  postgres-compose-network:
    driver: bridge